ports:
  - port: 8080
    onOpen: open-preview
  - port: 9856
    onOpen: ignore
tasks:
  - init: git submodule init && git submodule update && npm install --only=prod
    command: git submodule update && npm start
